"""`skillpod init` — bootstrap a project with a minimal skillfile.yml."""

from __future__ import annotations

from pathlib import Path

from skillpod.cli._output import emit, fail

_DEFAULT_MANIFEST = """\
# skillfile.yml — generated by `skillpod init`.
# Required keys are uncommented; commonly-tweaked optional keys are
# shown commented-out with their defaults. See examples/skillfile.yml
# in the skillpod repo for the full annotated reference.

version: 1

# Agents that receive symlink/copy/hardlink fan-out. An empty list means
# no fan-out happens (skills land only in .skillpod/skills/). Supported:
# claude, codex, gemini, cursor, opencode, antigravity.
agents:
  - claude

# install:
#   mode: symlink            # symlink | copy | hardlink   (default: symlink)
#   on_missing: error        # error | skip                (default: error)
#   fallback: [copy]         # tried when `mode` fails     (default: [copy])

# registry:
#   default: skills.sh
#   skills_sh:
#     allow_unverified: false
#     min_installs: 0
#     min_stars: 0

# Skills to install. Two equivalent forms:
#   - audit                          # shorthand
#   - { name: audit, source: ... }   # object form
skills: []
"""


def _ensure_gitignore_entry(project_root: Path) -> bool:
    """Append `.skillpod/` to `.gitignore` if missing. Return True if changed."""
    gi = project_root / ".gitignore"
    needle = ".skillpod/"
    if gi.exists():
        text = gi.read_text(encoding="utf-8")
        for line in text.splitlines():
            if line.strip() == needle:
                return False
        suffix = "" if text.endswith("\n") or not text else "\n"
        gi.write_text(text + suffix + needle + "\n", encoding="utf-8")
        return True
    gi.write_text(needle + "\n", encoding="utf-8")
    return True


def run(*, project_root: Path, manifest_path: Path, json_output: bool) -> None:
    if manifest_path.exists():
        raise fail(
            f"{manifest_path} already exists; refuse to overwrite",
            code=1,
            json_output=json_output,
        )

    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(_DEFAULT_MANIFEST, encoding="utf-8")
    gitignore_changed = _ensure_gitignore_entry(project_root)

    payload = {
        "ok": True,
        "manifest": str(manifest_path),
        "gitignore_updated": gitignore_changed,
    }
    human = (
        f"Wrote {manifest_path}\n"
        + ("Appended `.skillpod/` to .gitignore" if gitignore_changed else "")
    ).strip()
    emit(payload, json_output=json_output, human=human)


__all__ = ["run"]
